### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jvillard** [ocaml-community/yojson#113]
Hi yojson team, sorry to nudge but is there a plan to cut a new release? We use yojson a lot in [infer](/facebook/infer) and would love to switch to the next public release when available, eg to solve #85. Just wanted to let you know there is interest for a new release. Cheers.

**Comment by vphantom** [comment]
Perhaps a few of us could chip in and sponsor @Leonidas-from-XIV to work on it a bit? It'd be nice to inch closer to the cleanup that will be 2.0.0.

**Comment by Leonidas-from-XIV** [comment]
Hi @jvillard, @vphantom. Thanks for reaching out. We're discussing that internally to figure out a funding solution to make sure there is time to maintain Yojson.

**Comment by Leonidas-from-XIV** [comment]
With @panglesd on board now I think the development pace picked up and we'll be able to release 2.0.0 soon.

**Comment by Leonidas-from-XIV** [comment]
Aaaaand we have a 2.0.0 release! Grab it from OPAM while it's hot :tada:
