### ISSUE TITLE
Int overflow on 32bit architectures 

### ISSUE THREAD

**Issue by tmcgilchrist** [ocaml-community/yojson#120]
I expected (perhaps wrongly) that Yojson would use an underlying `int64` to parse json integer values into.
The following code fails on 32bit architectures (ARM/x86/ppc32) but passes on 64bit:
```ocaml
utop # Yojson.Basic.from_string {|
{"id": 1670148491}
|};;
Exception: Yojson.Json_error "Line 2, bytes 6-17:\nInt overflow '1670148491'".
```

The underlying issue is the use of `max_int` and `min_int` when parsing integer values at
https://github.com/ocaml-community/yojson/blob/b743857a28f02af68bcfadb515df0b21a9c6eb06/lib/read.mll#L81-L82

Slightly longer stacktrace showing the path from `Yojson.Basic.from_string` to the error
```
[exception] Yojson.Json_error("Line 1, bytes 6-17:\nInt overflow '1670148491'")
            Raised at Yojson.json_error in file "common.ml", line 5, characters 19-39
            Called from Yojson.Basic.read_json in file "lib/read.ml" (inlined), line 1025, characters 3-39
            Called from Yojson.Basic.__ocaml_lex_read_json_rec in file "lib/read.mll", line 238, characters 41-59
            Called from Yojson.Basic.read_json in file "lib/read.ml" (inlined), line 1025, characters 3-39
            Called from Yojson.Basic.__ocaml_lex_read_json_rec in file "lib/read.mll", line 258, characters 28-46
            Called from Yojson.Basic.read_json in file "lib/read.ml" (inlined), line 1025, characters 3-39
            Called from Yojson.Basic.from_lexbuf in file "lib/read.mll", line 1109, characters 8-26
            Called from Yojson.Basic.from_string in file "lib/read.mll", line 1122, characters 6-26
            Called from Dune__exe__Test.Make.test.(fun) in file "test/test.ml", line 55, characters 55-68
            Called from Alcotest_engine__Core.Make.protect_test.(fun) in file "src/alcotest-engine/core.ml", line 180, characters 17-23
            Called from Alcotest_engine__Monad.Identity.catch in file "src/alcotest-engine/monad.ml", line 24, characters 31-35
```

Before I start on making the change, would a PR fixing this issue be welcome?

**Comment by Leonidas-from-XIV** [comment]
I think this is because you're using `Basic` which doesn't include the `` `Intlit`` variant, so even if it could parse a number that exceeds the signed int31 range that OCaml supports on 32-bits, there is still no way to represent it in the output in the `Basic.t` type.

Note that `Yojson.Safe.from_string` should work and give you an `` `Intlit "1670148491"` (lacking a 32-bit system at hand I can't test), on 64-bits this works: `Yojson.Safe.from_string "4611686018427387904"`
