### ISSUE TITLE
Support of Windows-style line endings (\r\n)

### ISSUE THREAD

**Issue by maroneze** [ocaml-community/yojson#155]
I just tried parsing a JSON file produced under Windows (by Clang Power Tools, a Visual Studio extension; I then copy the file to Linux and run Yojson on it), and due to the presence of `\r\n`, parsing with Yojson fails. For instance, a simple file such as :

```json
[
    {
        "directory": "/tmp",
        "command": "",
        "file": "tmp.c"
    }
]
```

Results in:

```
Fatal error: exception Yojson.Json_error("Line 1, bytes 0-33:
Invalid token '﻿[
    {
        "directory":'")
```

I know I can just use `dos2unix` on the file, but as part of a complex pipeline to be used by less tech-savvy users, it might be useful if such step became unnecessary (it also avoids making the file unreadable on Windows).

Is there some official stance concerning support of such cases in Yojson? I didn't find it in the documentation.

Even if it's "not going to be supported anytime soon", it's fine for me, I'll just inform the user.

By the way, if there is a quick workaround that could be used e.g. before calling `Yojson.Safe.from_file`, it would also help.

**Comment by Leonidas-from-XIV** [comment]
Hi @maroneze, thanks for your report. I don't think that there is any official stance on not supporting DOS line endings, it's mostly just that none of the developers use operating systems with these line endings. But I agree that supporting these sounds reasonable. A PR fixing the lexer and adding some tests would certainly be welcome!

**Comment by c-cube** [comment]
https://www.json.org/json-en.html here I see that "whitespace" should include "linefeed" and "carriage return", so it's probably a bug that \r is not handled properly?

**Comment by Leonidas-from-XIV** [comment]
It's honestly surprising this hasn't been reported before.

**Comment by c-cube** [comment]
I think it's because, if you use yojson _on_ windows, the OCaml IO
channels will translate "\r\n" on the fly for you. Here the bug is
exposed by _copying_ a file to linux.

**Comment by mjambon** [comment]
> I think it's because, if you use yojson _on_ windows, the OCaml IO channels will translate "\r\n" on the fly for you. Here the bug is exposed by _copying_ a file to linux.

For this reason, I suggest opening files for reading systematically in binary mode and not using `input_line` because it doesn't recognize `\r\n` as a line ending. To enforce this, we use a [Semgrep rule for `open_in`](https://semgrep.dev/r?q=ocaml+open_in) and [another one for `input_line`](https://semgrep.dev/r?q=ocaml+input_line) on our code base.

**Comment by Costava** [comment]
What version of yojson is the issue reproducible with and what is a minimal snippet to hit the problem?

In `utop` with yojson 2.0.2, the following snippet runs successfully:
```ocaml
#require "yojson";;

let json_string = "{\r\n\t\"foobar\": 50,\r\n\t\"bar\": 71\r\n}"

let json = Yojson.Safe.from_string json_string

let () = Format.printf "Parsed to %a\n" Yojson.Safe.pp json;;
```
And prints:
```
Parsed to `Assoc ([("foobar", `Int (50)); ("bar", `Int (71))])
```

I don't see a test case in `test/compliance/test_cases/` that mentions carriage return --- is that what is keeping this issue open?

**Comment by Leonidas-from-XIV** [comment]
@Costava I've added a test.

The tests in `test/compliance/test_cases` can't test for CRLF as they get opened by `open_in` as @mjambon mentions thus if they had `\r\n` it would be normalized to `\n`. While I agree that using `open_in_bin` is the better way, even without that we seem to parse these line endings just fine.
