### ISSUE TITLE
Add @NathanReb to project owners

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/yojson#68]
@NathanReb is [kindly taking over the maintenance of yojson](https://discuss.ocaml.org/t/wanted-new-maintainer-for-yojson/2966) with support from Cryptosense. Can @pmetzger or someone with admin permissions please make him a project owner?

**Comment by Leonidas-from-XIV** [comment]
As far as I see this is done and can be closed 🙂

**Comment by pmetzger** [comment]
@NathanReb can you close this, please?
