### ISSUE TITLE
Docs seem to be down

### ISSUE THREAD

**Issue by ostera** [ocaml-community/yojson#72]
Just reporting here that going to https://ocaml-community.github.io/yojson/ gives me a 404.

**Comment by NathanReb** [comment]
Thanks for reporting! Next release will fix that, I'll take care of it right away!

**Comment by NathanReb** [comment]
@pmetzger I can't enable github pages for this repo. Could you please set it up or grant me access rights so I can do it myself?

Don't know what's the most convenient option here.

**Comment by pmetzger** [comment]
I can set it up; just tell me what I need to do.

**Comment by NathanReb** [comment]
Awesome, thanks!

It might be something else but if you could follow the steps at https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ and make sure github pages is set up and tracks the `gh-pages` branch and let me know that would be great.

**Comment by pmetzger** [comment]
Sorry. I opened the page up, there looked like there were a lot of steps, and I promptly forgot about it. Can you be more specific about what steps need to be done?

**Comment by NathanReb** [comment]
Can you try that part ?

![screenshot from 2019-01-29 17-53-59](https://user-images.githubusercontent.com/7419360/51925260-f5878a00-23ee-11e9-865f-ae2839bf7cbb.png)

As I said I'm not 100% sure that will fix it but it appears to indeed be a repo misconfiguration since pushing the github-page to my fork did the trick and the doc is available from my github pages.

**Comment by pmetzger** [comment]
What counts as our "github pages site's repository"? We only get _one_ github pages repo, right?

**Comment by Leonidas-from-XIV** [comment]
Each repository gets its own github-pages url, this one's would be https://ocaml-community.github.io/yojson, so the setting to enable it would be here: https://github.com/ocaml-community/yojson/settings

**Comment by pmetzger** [comment]
So, it already seems to have been set...

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1907413/51944539-4d6fc200-23ea-11e9-8298-e26c77d6e298.png">

**Comment by Leonidas-from-XIV** [comment]
Strange, when I pull gh-pages and push it to my repo I get this:

<img width="742" alt="screenshot 2019-01-29 at 23 27 16" src="https://user-images.githubusercontent.com/121531/51944918-7e1d1f00-241d-11e9-910c-b3ee5cc6d37e.png">

And https://leonidas-from-xiv.github.io/yojson/ displays the docs as expected. I've [reached out to GitHub support](https://twitter.com/leonidasfromxiv/status/1090376557108039682) about this.

**Comment by Leonidas-from-XIV** [comment]
The mystery is solved, as the GitHub support explained to me:

> In order to be built and published for the very first time, a GitHub Pages repository must have a commit pushed to it by a user with admin permissions for the repository, such as the repository owner.
>
> In this case, it looks like the only commits pushed to the repository were from users with write permissions, not admin permissions.
>
> Once a commit has been pushed to the repository by a user with admin permissions, you should find the site live and available shortly thereafter. Subsequent commits pushed by accounts with write access will then also trigger a build.

Which explains why it works on our own forks but not on ocaml-community. So @pmetzger, can you push a commit to the `gh-pages` branch? I would suggest just doing a `git commit --allow-empty`, that should be enough to mark it as enabled.

**Comment by pmetzger** [comment]
Well, that was a stupid thing. Anyway, I just did it, and https://ocaml-community.github.io/yojson/ now seems to have content.

**Comment by NathanReb** [comment]
Great! Thank you very much!
