### ISSUE TITLE
Missing Yojson.Raw.Util module

### ISSUE THREAD

**Issue by wizeman** [ocaml-community/yojson#96]
The Yojson.Raw module doesn't seem to have a Util submodule, unlike Yojson.Basic and Yojson.Safe.

It would be nice to have it.

**Comment by tmcgilchrist** [comment]
Have a look at this change https://github.com/tmcgilchrist/yojson/commit/4634ee56a5d43866faa93322e75b18f5b2867c5d

Some of the functions become of questionable use after you CPP out `INT` and `FLOAT`. 
What functions in Yojson.Raw.Util would you need?

**Comment by hhugo** [comment]
This issue should probably be closed since #163 has been merged
